language: objective-c

before_script:
  - sudo gem install calabash-cucumber

script:
  - xcodebuild -project FTTDDTest.xcodeproj -scheme FTTDDTest-cal -configuration DEBUG -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO TARGETED_DEVICE_FAMILY=1
  - cucumber
