language: objective-c

before_script:
  - sudo gem install calabash-cucumber

script:
  - xcodebuild -project FTTDDTest.xcodeproj -scheme FTTDDTest-cal -configuration Debug -sdk iphonesimulator clean build
  - cucumber
